### ISSUE TITLE
Default arguments not explained yet?

### ISSUE THREAD

**Issue by marshallhelenm** [learn-co-curriculum/programming-univbasics-3-ruby-method-arguments-lab#1]
Hiya! I figured it out via some googling, but this lesson seems to indicate that the student should already have been told how to make a default value for an argument, but I can't find that anywhere in the lessons on methods so far. If I was meant to experiment or google to figure it out then mission accomplished, but it seemed to me like something was missing.

**Comment by maxwellbenton** [comment]
Hi @marshallhelenm,

Thank you for providing this feedback. We've updated the previous lesson on method arguments to include a section introducing default arguments just prior to this lab.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by marshallhelenm** [comment]
Thanks a bunch! Like I said, I figured it out, but glad to help things keep
improving. :)
