### ISSUE TITLE
Methods and Arguments Lab

### ISSUE THREAD

**Issue by tragan712** [learn-co-curriculum/programming-univbasics-3-ruby-method-arguments-lab#2]
```ruby
def introduction(name) 
  puts "Hi, my name is #{name}." 
end 

def introduction_with_language(name, language) 
    puts "Hi, my name is #{name} and I am learning to program in #{language}." 
 end
 
def introduction_with_language_optional(name, language) 
    puts "Hi, my name is #{name} and I am learning to program in #{language}." 
    language="Ruby"
 end
```

    Finished in 0.00474 seconds (files took 0.32159 seconds to load)
4 examples, 1 failure

Failed examples:

rspec ./spec/introduction_spec.rb:18 # #introduction_with_language_optional takes in two arguments, a name and a language, and language defaults to Ruby

Why??? Please help. I dont have the option to get help or ask qiustions. Couple of issuses but this is most pressing.

**Comment by sgharms** [comment]
@tragan712 

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab.

Use the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, for some reason, AAQ doesn't work, please let us know here so we can fix it.

To keep your progress going, I'll point out that you might want to re-examine the content on setting default arguments.

If you believe there is a bug in our code, please re-open this case and we'll address promptly.
